// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8_6MRI9GGV4VVrmDjpE8YjOIuD6BeGPs',
    appId: '1:927889873387:web:21fe7d8e167d740d7fa1ae',
    messagingSenderId: '927889873387',
    projectId: 'clientmanageapp',
    authDomain: 'clientmanageapp.firebaseapp.com',
    storageBucket: 'clientmanageapp.firebasestorage.app',
    measurementId: 'G-DBHWQ90SC2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoupFpPDqDQUi1p1Q3gUX7L2A0-PehdVY',
    appId: '1:927889873387:android:a1297c2405789bbf7fa1ae',
    messagingSenderId: '927889873387',
    projectId: 'clientmanageapp',
    storageBucket: 'clientmanageapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHmh453rdsHw_fPXiULUKm7ZpDlW7EI8M',
    appId: '1:927889873387:ios:3392110c7d40147d7fa1ae',
    messagingSenderId: '927889873387',
    projectId: 'clientmanageapp',
    storageBucket: 'clientmanageapp.firebasestorage.app',
    iosBundleId: 'com.example.clientManage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHmh453rdsHw_fPXiULUKm7ZpDlW7EI8M',
    appId: '1:927889873387:ios:3392110c7d40147d7fa1ae',
    messagingSenderId: '927889873387',
    projectId: 'clientmanageapp',
    storageBucket: 'clientmanageapp.firebasestorage.app',
    iosBundleId: 'com.example.clientManage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8_6MRI9GGV4VVrmDjpE8YjOIuD6BeGPs',
    appId: '1:927889873387:web:f7ebd64904605a8c7fa1ae',
    messagingSenderId: '927889873387',
    projectId: 'clientmanageapp',
    authDomain: 'clientmanageapp.firebaseapp.com',
    storageBucket: 'clientmanageapp.firebasestorage.app',
    measurementId: 'G-4QRC0PD98P',
  );
}
